### ISSUE TITLE
TestNG (version 5.7) seems to no longer work on JDK1.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testng-team/testng-googlecode#14]
```
What steps will reproduce the problem?
1. upgrade to eclipse-testng version 5.7 which presumably uses testng 5.7 
under the hood
2. run a test based on JDK1.4 (Javadoc annotations)
3. NoSuchMethodError occurs.

What is the expected output? What do you see instead?
expected: works as before ;-).

instead:
java.lang.NoSuchMethodError: java.lang.String.replace
(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;
    at 
org.testng.remote.strprotocol.MessageHelper.replaceUnicodeCharactersWithAsc
ii(MessageHelper.java:149)
    at org.testng.remote.strprotocol.TestResultMessage.<init>
(TestResultMessage.java:84)
    at org.testng.remote.strprotocol.TestResultMessage.<init>
(TestResultMessage.java:99)
    at 
org.testng.remote.strprotocol.RemoteMessageSenderTestListener.onTestFailure
(RemoteMessageSenderTestListener.java:64)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1386)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1370)

What version of the product are you using? On what operating system?
eclipse europa + testng 5.7, windows.

Please provide any additional information below.
JDK1.5 API used in MessageHelper. String.replace(CharSequence, 
CharSequence) does not yet exist in 1.4 API.
When running the same test in a 1.5 JRE, it works flawlessly.


```

Original issue reported on code.google.com by `oliver.m...@gmail.com` on 4 Oct 2007 at 9:51
